### ISSUE TITLE
Änderung unter Angebot, Kosten

### ISSUE THREAD

**Issue by esther7bieri** [psychotherapie-bieri/psychotherapie-bieri.github.io#14]
![image](https://user-images.githubusercontent.com/39628439/40562884-176eac16-6063-11e8-889e-d495cfeaa777.png)

**Comment by netzwerg** [comment]
Ok so? https://psychotherapie-bieri-test.github.io/angebot.html

Oder soll irgendwo das Wort "Krankenkasse" wieder fett sein, damit man es schneller sieht?

**Comment by esther7bieri** [comment]
Das ist tiptop so, danke! Ich denke, wir machen die KK nicht mehr fett. Die
beiden Abschnittchen zum Thema Opferhilfe und Unfallversicherung kommen ja
dann noch weg (die Opferhilfe hat es lieber, wenn die Leute zu delegiert
arbeitenden TherapeutInnen gehen und die Unfallversicherung nimmt es auch
sehr genau...).

E achöne Obe!

**Comment by netzwerg** [comment]
Ah, sorry für die Verwirrung, jetzt habe ich erst das Issue mit der Opferhilfe und der Unfallversicherung gesehen...  alles klar!

**Comment by esther7bieri** [comment]
Super, danke!
